// This file is automatically generated. Do not modify it manually.

package main

import (
	"encoding/json"
	"strings"

	"github.com/mattermost/mattermost/server/public/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "mattermost-dev-environment",
  "name": "Mattermost Dev Environment",
  "description": "This plugin contains some helpful functionality pertaining to the Mattermost dev environment.",
  "homepage_url": "https://github.com/mickmister/mattermost-plugin-dev-environment",
  "support_url": "https://github.com/mickmister/mattermost-plugin-dev-environment/issues",
  "release_notes_url": "https://github.com/mickmister/mattermost-plugin-dev-environment/releases/tag/v0.1.0",
  "icon_path": "assets/starter-template-icon.svg",
  "version": "0.1.0",
  "min_server_version": "5.12.0",
  "server": {
    "executables": {
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "Plugin needs to be restarted for these settings to take effect.",
    "footer": "",
    "settings": [
      {
        "key": "numlines_error_truncate",
        "display_name": "Number of lines for errors",
        "type": "number",
        "help_text": "Number of lines to truncate javascript errors. Set blank to avoid truncating.",
        "placeholder": "",
        "default": 3,
        "hosting": ""
      },
      {
        "key": "numlines_warning_truncate",
        "display_name": "Number of lines for warnings",
        "type": "number",
        "help_text": "Number of lines to truncate javascript warnings. Set blank to avoid truncating.",
        "placeholder": "",
        "default": 3,
        "hosting": ""
      }
    ]
  }
}
`

func init() {
	_ = json.NewDecoder(strings.NewReader(manifestStr)).Decode(&manifest)
}
